import { TemplateRouteInterface } from 'src/router/routes';

export const defaultRouter: TemplateRouteInterface[] = [
  {
    path: '/',
    name: 'Layouts',
    componentPath: 'layouts',
    component: 'tabs.vue',
    children: [
      {
        path: '/',
        name: 'register',
        componentPath: 'pages',
        component: 'index.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/login',
        name: 'login',
        componentPath: 'pages',
        component: 'login.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/forgot',
        name: 'forgot',
        componentPath: 'pages',
        component: 'forgot.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/info',
        name: 'info',
        componentPath: 'pages',
        component: 'info.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/setting',
        name: 'setting',
        componentPath: 'pages',
        component: 'setting.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/info/edit',
        name: 'infoEdit',
        componentPath: 'pages',
        component: 'infoEdit.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/new/password',
        name: 'newPassword',
        componentPath: 'pages',
        component: 'newPassword.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/update/password',
        name: 'updatePassword',
        componentPath: 'pages',
        component: 'updatePassword.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/new/code',
        name: 'newCode',
        componentPath: 'pages',
        component: 'newCode.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/update/code',
        name: 'updateCode',
        componentPath: 'pages',
        component: 'updateCode.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/language',
        name: 'language',
        componentPath: 'pages',
        component: 'language.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/about',
        name: 'about',
        componentPath: 'pages',
        component: 'about.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/privacy/policy',
        name: 'privacyPolicy',
        componentPath: 'pages',
        component: 'privacyPolicy.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/enter/email',
        name: 'enterEmail',
        componentPath: 'pages',
        component: 'enterEmail.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/authentication',
        name: 'authentication',
        componentPath: 'pages',
        component: 'authentication.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/verifyt',
        name: 'verifyt',
        componentPath: 'pages',
        component: 'verifyt.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
    ],
    meta: {},
  },
  {
    path: '/team/benefits',
    name: 'teamBenefits',
    componentPath: 'pages',
    component: 'team/benefits.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/team/management',
    name: 'teamManagement',
    componentPath: 'pages',
    component: 'team/management.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/share',
    name: 'defaultShare',
    componentPath: 'pages',
    component: 'share.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/help/center',
    name: 'helpCenter',
    componentPath: 'pages',
    component: 'helpCenter.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/download',
    name: 'download',
    componentPath: 'pages',
    component: 'download.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/identification',
    name: 'identification',
    componentPath: 'pages',
    component: 'identification.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
];
