import { TemplateRouteInterface } from 'src/router/routes';

export const defaultRouter: TemplateRouteInterface[] = [
  {
    path: '/',
    name: 'Layouts',
    componentPath: 'layouts',
    component: 'tabs.vue',
    children: [
      {
        path: '/',
        name: 'Home',
        componentPath: 'pages',
        component: 'index.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/',
        name: 'Notice',
        componentPath: 'pages',
        component: 'notice.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
      {
        path: '/',
        name: 'User',
        componentPath: 'pages',
        component: 'user.vue',
        children: [],
        meta: { requireAuth: false, keepAlive: false },
      },
    ],
    meta: {},
  },
  {
    path: '/team/benefits',
    name: 'teamBenefits',
    componentPath: 'pages',
    component: 'team/benefits.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/team/management',
    name: 'teamManagement',
    componentPath: 'pages',
    component: 'team/management.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/share',
    name: 'defaultShare',
    componentPath: 'pages',
    component: 'share.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/help/center',
    name: 'helpCenter',
    componentPath: 'pages',
    component: 'helpCenter.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/download',
    name: 'download',
    componentPath: 'pages',
    component: 'download.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
  {
    path: '/identification',
    name: 'identification',
    componentPath: 'pages',
    component: 'identification.vue',
    children: [],
    meta: { requireAuth: false, keepAlive: false },
  },
];
